services:
  scheduler:
    container_name: scheduler
    build:
      context: ./src/scheduler
      dockerfile: scheduler.Dockerfile
    restart: unless-stopped
    env_file:
      - ./src/scheduler/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  backend:
    build:
      context: ./src/backend
      dockerfile: backend.Dockerfile
    container_name: backend
    expose:
      - "8000"
    env_file:
      - ./src/backend/.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: frontend.Dockerfile
    volumes:
      - ./src/frontend/dist:/host_dist
    command: sh -c "rm -rf /host_dist/* && cp -r /app/dist/* /host_dist/"
    container_name: frontend
    restart: "no"

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/frontend/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: bullbear_network
