# Generated by Django 5.2.7 on 2025-12-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentquote',
            name='instrument',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
