name: Notify Discord

on:
  push:        # sada obuhvaća sve grane
    branches:
      - '**'
  pull_request:
    types: [opened, reopened, closed, merged]
  issues:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare message
        id: prepare
        run: |
          EVENT_NAME="${{ github.event_name }}"
          ACTOR="${{ github.actor }}"
          REPO="${{ github.repository }}"

          case "$EVENT_NAME" in
            push)
              BRANCH="${GITHUB_REF#refs/heads/}"
              COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
              COMMIT_URL="${{ github.event.head_commit.url }}"
              MESSAGE="**🟢 Novi commit u repozitoriju $REPO**\nGrana: \`$BRANCH\`\nAutor: $ACTOR\nPoruka: $COMMIT_MESSAGE\n[Pregledaj commit]($COMMIT_URL)"
              ;;
            issues)
              ISSUE_TITLE="${{ github.event.issue.title }}"
              ISSUE_URL="${{ github.event.issue.html_url }}"
              ACTION="${{ github.event.action }}"
              MESSAGE="**🟣 Issue $ACTION u $REPO**\nAutor: $ACTOR\nNaslov: $ISSUE_TITLE\n[Pregledaj issue]($ISSUE_URL)"
              ;;
            pull_request)
              PR_TITLE="${{ github.event.pull_request.title }}"
              PR_URL="${{ github.event.pull_request.html_url }}"
              ACTION="${{ github.event.action }}"
              MESSAGE="**🔵 Pull Request $ACTION u $REPO**\nAutor: $ACTOR\nNaslov: $PR_TITLE\n[Pregledaj PR]($PR_URL)"
              ;;
            *)
              MESSAGE="⚪ Nepodržani događaj: $EVENT_NAME"
              ;;
          esac

          echo "message=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Send notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"${{ steps.prepare.outputs.message }}\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
