name: Notify Discord on Push

on:
  push:
    branches:
      - '**'

jobs:
  notify_push:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare message
        id: prepare
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${GITHUB_REF#refs/heads/}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          ACTOR="${{ github.actor }}"
          MESSAGE="**🟢 Novi commit u repozitoriju $REPO**\nGrana: \`$BRANCH\`\nAutor: $ACTOR\nPoruka: $COMMIT_MESSAGE\n[Pregledaj commit]($COMMIT_URL)"
          # write multi-line output safely
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send notification to Discord
        run: |
          python3 - <<'PY'
import json
content = """${{ steps.prepare.outputs.message }}"""
print(json.dumps({"content": content}))
PY > body.json
          curl -H "Content-Type: application/json" -X POST -d @body.json ${{ secrets.DISCORD_WEBHOOK }}
